config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  
  root 'articles#index'
  
  resources :articles do
    resources :comments
  end
  
  resources :comments, only: [:destroy]
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    
    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :student
      can [:index, :show, :new, :create], Article
      can [:edit, :update, :destroy], Article, user_id: user.id
      can :destroy, Comment, user_id: user.id
      can [:create], Comment
    else
      can [:index, :show], Article
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  resourcify
  
  belongs_to :user
  has_many :comments, dependent: :destroy
  mount_uploader :bird, BirdUploader
  paginates_per 2
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :article
    belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  
  after_create :assign_default_role
  
  def assign_default_role
    add_role(:student)
  end
  
  has_many :articles
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_locale
  def set_locale
    if [RailsAdmin].include?(self.class.parent)
      I18n.locale = :en
    else
      I18n.locale = params[:locale] || I18n.default_locale
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource param_method: :params_article
  def index
    # @articles = Article.all
    @articles = Article.order("created_at DESC").page(params[:page])
  end
  
  def show
    @article = Article.find(params[:id])
    @comments = @article.comments
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(params_article)
    
    if @article.save
      flash[:notice] = "글 작성 완료"
      redirect_to @article
    else
      flash[:notice] = "글 작성 중 오류"
      redirect_to new_article_path
    end
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  def update
    @article = Article.find(params[:id])
    
    if @article.update(params_article)
      flash[:notice] = "글 수정 완료"
      redirect_to @article
    else
      flash[:notice] = "글 수정 중 오류"
      redirect_to edit_article_path
    end
  end
  
  def destroy
    @article = Article.find(params[:id])
    
    if @article.destroy
      flash[:notice] = "글 삭제 완료"
    else
      flash[:notice] = "글 삭제 오류"
    end
    
    redirect_to articles_path
  end
  
  private
    def params_article
      params.require(:article).permit(:title, :content, :bird, :user_id)
    end
    
    def check_authorized_user
      if current_user.id != @article.user.id
        flash[:notice] = "해당 글에 대한 권한이 없습니다."
        redirect_back fallback_location: root_path
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new(params_comment)
    @comment.save
    
    redirect_to @article
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    
    @comment.destroy
    
    redirect_back fallback_location: root_path
  end
  
  private
    def params_comment
      params.require(:comment).permit(:body, :user_id)
    end
    
    def check_authorized_user
      if current_user.id != @article.user.id
        flash[:notice] = "해당 글에 대한 권한이 없습니다."
        redirect_back fallback_location: root_path
      end
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<div class="card">
  <div class="card-body">
    <%= form_for @article do |form| %>
     <div class="field">
       <%= form.label :title %><br>
       <%= form.text_field :title, id: :article_title %>
     </div><br>
        
     <div class="field">
       <%= form.label :content %><br>
       <%= form.text_area :content, id: :article_content %>
     </div><br>
     
     <div class="field">
        <%= form.label :bird, '사진' %><br>
        <%= form.file_field :bird, class: "img_input", onchange: "loadFile(event)", accept: "image/*" %>
     </div><br>
     
     <%= form.hidden_field :user_id, value: current_user.id %>
     
     <div>
        <img src="#" alt="미리보기" id="preview" style="width: 250px;"/>
     </div><br>
     
     <div class="card-link">
       <%= form.submit "글 쓰기", class: "btn btn-primary" %>
     </div>
    <% end %>
  </div>
</div>

<script>
  var loadFile = function(event) {
    var preview = document.getElementById('preview');
    preview.src = URL.createObjectURL(event.target.files[0]);
  };
</script>

app/views/articles/edit.html.erb
<h2>글 수정</h2>
<br>
<%= render 'form', article: @article %>
<br>
<%= link_to '뒤로가기', articles_path %>

app/views/articles/index.html.erb
<h3>글 목록</h3>
<table class="table">
    <thead>
        <tr>
            <th>#</th> 
            <th>제목</th>
            <th colspan="3">-</th>
        </tr>
    </thead>
    <tbody>
        <% @articles.each do |article| %>
            <tr>
                <td><%= article.id %></td>
                <td><%= article.title %></td>
                <td><%= link_to '보기', article %></td>
                <% if current_user.present? %>
                    <% if can? :update, article %>
                        <td><%= link_to '수정', edit_article_path(article) %></td>
                    <% end %>
                    <% if can? :destroy, article %>
                        <td><%= link_to '삭제', article, method: :delete, data: {confirm: "정말로 삭제?"} %></td>
                    <% end %>
                <% end %>
            </tr>
        <% end %>
    </tbody>
</table>
<%= link_to '글 쓰기', new_article_path, class: "btn btn-primary float-right" %><br>

<div class="page-num" style="margin: 0 auto; width: 200px;">
    <%= paginate @articles %>
</div>

app/views/articles/new.html.erb
<h2>새 글 작성</h2>
<br>
<%= render 'form', article: @article %>
<br>
<%= link_to '뒤로가기', articles_path %>

app/views/articles/show.html.erb
<div class="card" style="width: 50rem;">
  <div class="card-header">
    <h5 class="card-title">제목 : <%= @article.title %></h5>
    <p class="float-right">작성자 : <%= @article.user.name %></p>
  </div>
  <div class="card-body">
    <h5 class="card-text">내용</h5><hr>
    <img class="card-img-top" src="<%= @article.bird.url %>" alt="사진 없음" style="width:18rem;"/>
    <p class="card-text"><%= @article.content %></p>
    <% if current_user.present? %>
      <% if can? :update, @article %>
        <%= link_to '수정', edit_article_path(@article), class: "btn btn-primary" %>
      <% end %>
      <% if can? :destroy, @article %>
        <%= link_to '삭제', @article, method: :delete, data: {confirm: "정말로 삭제?"}, class: "btn btn-secondary" %>
      <% end %>
    <% end %>
  </div>
</div><br>

<% if current_user.present? %>
  <%= render 'comments/form' %><br>
<% else %>
  <div class="alert alert-light">
    댓글은 로그인 하셔야 작성할 수 있습니다.
  </div>
<% end %>
<%= render 'comments/index' %><br>


<%= link_to '목록으로', articles_path %>

app/views/comments/_form.html.erb
<div class="card" style="width: 50rem;">
  <div class="card-body">
    <h5 class="card-title">댓글 쓰기</h5>
    <%= form_for :comment, url: article_comments_path(@article.id) do |f| %>
      <p>
        <%= f.label :body, '내용' %><br>
        <%= f.text_area :body, :cols => 50, :rows => 1 %>
      </p>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <p>
        <%= f.submit '작성', class: 'btn btn-secondary' %>
      </p>
    <% end %>
  </div>
</div>

app/views/comments/_index.html.erb
<% if @comments.present? %>
<div class="card" style="width: 50rem">
  <div class="card-body">
    <h5 class="card-title">댓글 목록</h5>
    <ul class="list-group list-group-flush">
    <% @comments.each do |comment| %>
      <li class="list-group-item"><%= comment.body %>
        <p class="float-right"> 작성자 : <%= comment.user.name %>
          <% if current_user.present? %>
            <% if can? :destroy, comment %>
              <span class="float-right"> | <%= link_to '삭제', comment, method: :delete, data: {confirm: "댓글 삭제 진짜해요?"} %></span>
            <% end %>
          <% end %>
        </p>
      </li>
    <% end %>
    </ul>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
</head>
<body style="margin: 6rem;">
  <header>
    <div class="jumbotron">
      <div class="container">
        <h3 class="display-7">충북대 X 멋사 6기</h1>
        <nav style="float:right" >
          <ul class="nav">

              <% if user_signed_in? %>
                <% if current_user.has_role? :admin %>
                  <li class="nav-item">
                    <a class="nav-link deactivate"><%=link_to '관리자페이지', rails_admin_path, class: "nav-link"%></a>
                  </li>
              <% end %>

              <li class="nav-item">
                <a class="nav-link deactivate"><%= current_user.email %></a>
              </li>
              <li class="nav-item">
                <a class="nav-link deactivate">
              </li>
              <li class="nav-item">
                <%= link_to '로그아웃', destroy_user_session_path, method: :delete, class: "nav-link" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to '회원가입', new_user_registration_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to '로그인', new_user_session_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>
  </header>
  
  <hr>

  <div class="container">
  
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    
    <%= yield %>
  </div>
</body>
</html>